// Creates src/preact-demo/vendored-panel.js from @bpmn-io/properties-panel (MIT).
//
// The npm package imports Preact through relative paths ('../preact/hooks'),
// which point to a Preact copy bundled inside the package. The vendored copy
// changes only those imports, so the panel uses the same Preact as the host.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(join(root, 'package.json'));

let pkgDir;
try {
  pkgDir = dirname(require.resolve('@bpmn-io/properties-panel/package.json'));
} catch {
  console.log('[vendor-panel] @bpmn-io/properties-panel not installed yet, skipping');
  process.exit(0);
}

const { version } = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf8'));
const source = readFileSync(join(pkgDir, 'dist', 'index.esm.js'), 'utf8');

let count = 0;
const withoutSourceMap = source.replace(/^\/\/# sourceMappingURL=.*$/m, '');
const vendored = withoutSourceMap.replace(/from '\.\.\/preact((?:\/[a-z-]+)?)'/g, (_, sub) => {
  count++;
  return `from 'preact${sub}'`;
});

if (count === 0) {
  throw new Error('[vendor-panel] no relative Preact imports found, check the package version');
}

const target = join(root, 'src', 'preact-demo', 'vendored-panel.js');
mkdirSync(dirname(target), { recursive: true });
const header = `// GENERATED by scripts/vendor-panel.mjs - do not edit.
// Copy of @bpmn-io/properties-panel@${version} dist/index.esm.js (MIT License, bpmn.io).
// Only change: ${count} imports from '../preact/*' were rewritten to 'preact/*'.
`;
writeFileSync(target, header + vendored);
console.log(`[vendor-panel] wrote src/preact-demo/vendored-panel.js (${count} imports rewritten, panel ${version})`);
